# Generated by Django 6.0.3 on 2026-04-05 14:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='inventory',
            field=models.PositiveIntegerField(verbose_name=django.core.validators.MinValueValidator(1)),
        ),
    ]
