# Generated by Django 6.0.3 on 2026-03-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('membership', models.CharField(choices=[('S', 'silver'), ('B', 'Bronze'), ('G', 'Gold')], default='B', max_length=1)),
            ],
        ),
    ]
